### PR TITLE
implement routes for login, signup, get all users, and get one user's info, fixes #11

### LINKED ISSUE #11: API responds with status code 201 even though user creation failed

### PR DESCRIPTION
**Pull request by sarchila**
server responds to successful login and signup requests with a "Location" header that contains the URL for the user

### CODE REVIEW

**Comment by Hendrixer** [comment]
yo, you got some trailing white spaces on your coffee man. Check out the Travis details and see why, otherwise, good job!

**Comment by sarchila** [comment]
Whoops... I ran grunt coffee on my code, but I realize now that it doesn't lint it anymore, just compiles... thought it was linting.. :-/

**Comment by Hendrixer** [comment]
Yea,my bad,its grunt build that does both

**Comment by stateoflux** [comment]
can I go ahead and merge this?

**Comment by stateoflux** [comment]
Hey Santiago,  I not sure what utility setting the location header has to me.  I'd rather you send the 201 status plus a JSON object like the following: 
 {
  "createdAt": "2011-11-07T20:58:34.448Z",
  "objectId": "g7y9tkhB7O",
  "sessionToken": "pnktnjyb996sj4p156gjtp4im"
}

**Comment by Hendrixer** [comment]
Don't merge it yet. Its got some errors and we'll update it to be the
object that you need Wayne

**Comment by sarchila** [comment]
Yeah, I can send back JSON in addition.  I just set the location header bc that's what Parse does, and it sounded like a decent idea...

**Comment by Hendrixer** [comment]
Cool, Santiago, update your pull request

**Comment by sarchila** [comment]
Okay, I added a couple commits

**Comment by Hendrixer** [comment]
good work team

**Comment by stateoflux** [comment]
hey scott.  I don't see the CORs config in "middleware.coffee.", did you forget to add?

**Comment by Hendrixer** [comment]
No, I haven't pushed mime up yet, I was waiting on Santiago , just adding
my stuff on top of his now

**Comment by stateoflux** [comment]
ok cool.

**Pull request merged**
